### ISSUE TITLE
ios - works fine in debug build but not release build

### ISSUE THREAD

**Issue by timothylui** [rome2rio/react-native-touch-through-view#1]
Hi, I'm using this library with a scroll view over a react-native-map, in debug build it works fine, I can click on map markers but when I do a release build the touch through no longer works and it only scrolls the scrollview.

**Comment by timothylui** [comment]
Hey, any updates on this?

**Comment by martsie** [comment]
I won't have a chance to look into this for a few weeks however I'm open to PR's or any additional information. If you look at the source for the iOS side the native code is very very simple so it shouldn't be too hard to debug (Android is a bit more complex).

If the same issue exists on Android it's likely to be an issue with the JavaScript side, if not then the native side.

**Comment by martsie** [comment]
I've issued a pull request for this ... should hopefully be approved soon by one of the team members at Rome2rio. It's so hard debugging release code issues.

**Comment by timothylui** [comment]
Thanks, fix works for me
