### ISSUE TITLE
RN 48+ Android issues

### ISSUE THREAD

**Issue by kristfal** [rome2rio/react-native-touch-through-view#8]
In order to support the latest RN version (cant recall if this was changed in 48 or later), we'll need to drop the `@override` from `createJSModules` in `TouchThroughViewPackage.java`.

The open PRs to propTypes should also be merged to support the latest RN version.

**Comment by kristfal** [comment]
On top of this, I'm getting redbox errors due to `SimpleViewManager` not being castable to `ViewGroupManager` using RN 0.50.3. If I do change the view manager to `ViewGroupManager`, the app runs fine but touches are not passed through. 

Any tips on how to proceed?

**Comment by RichardLindhout** [comment]
@kristfal We're having the same problem at the moment.

**Comment by RichardLindhout** [comment]
A colleague is looking into it. Maybe we can add or remove some code which will send the touch event through.

**Comment by martsie** [comment]
Thanks @RichardLindhout ... if you get a patch happening I'll message Rome2rio and try to push it through

**Comment by martsie** [comment]
I've referenced this issue in the Readme to be as transparent as possible to new users.

**Comment by simonhoss** [comment]
Can someone tell me on which react-native version this works? I'm currently thinking to make a downgrade. At the moment we are on 0.47.1

**Comment by ianmartorell** [comment]
Is there an update on this? I'd like to use this package with 0.50.3. I can try to look into the issue if no one else is working on it.

**Comment by simonhoss** [comment]
I think some trying to find a solution, but without success until now. If you find a solution then this would be awesome

**Comment by simonhoss** [comment]
I made a PR with a possible fix. Im not super happy with it but I didn't found any other solution, except registering it to the app activity.

**Comment by RichardLindhout** [comment]
@simonhoss Thanks a lot!

Seems this function is not used?

```
  //If the touch was not on the list make the slop rect small so react-native dont use this view as responder
 +    public Rect getHitSlopRect() {
 +        if (lastTouchWasNotValid) {
 +            return new Rect(-1000, -1000, -1000, -1000);
 +        }
 +        return new Rect(0, 0, 0, 0);
 +    }
```

**Comment by simonhoss** [comment]
This is the main function to prevent react-native using this view. This function comes from the interface `ReactHitSlopView`

**Background:**
Every time you touch something in react-native it goes through the views and try to figure out the correct view for the target based on the touch position. I figured out that react-native uses the `getHitSlopRect` when it exists. The idea of the `getHitSlopRect` is, that you can make a touch area bigger when you have for example a small button. I used it now to make the touch area super small, so that the the view cannot be the target. That's also the reason why we have to register the touch in the activity and before react-native uses the touch and goes through the view tree, because the `getHitSlopRect` is checked before the touch method is called for the view.

**Comment by kristfal** [comment]
@RichardLindhout Hey! Want to merge this one in (along with the other fixes), or would you consider this repo stale?

**Comment by martsie** [comment]
If you folks have tested any PR's and are happy with them then I can merge and publish - just let me know which ones :) I'm not currently using this library in my projects so I'm relying on you fine people to test changes.

**Comment by ianmartorell** [comment]
Have you guys tried using View's [`pointerEvents`](https://facebook.github.io/react-native/docs/view.html#pointerevents) prop? It solved my specific use case.

**Comment by simonhoss** [comment]
The problem is when you use pointerEvents that you set the pointerEvents on the transparent header view. When you now try to press a button which is behind that transparent header then the button gets not triggered, because the List which fills the complete screen is the responder.

**Comment by martsie** [comment]
pointerEvents doesn't transmit its events through scroll views. See the examples on the project page to get an idea of use cases where you'd need to use this over pointerEvents.

**Comment by DVSoftware** [comment]
Any update on this one?

**Comment by derekblank** [comment]
@simonhoss I'm trying your solution, which looks promising. I'm using react-native-navigation, however, which requires that we extend `com.reactnativenavigation.controllers.SplashActivity` [instead of `ReactActivity`](https://wix.github.io/react-native-navigation/#/installation-android) in `MainActivity.java`. 

I attempted to merge the two with the following:

```
package com.myapp;

import com.reactnativenavigation.controllers.SplashActivity;
import android.view.MotionEvent;
import com.rome2rio.android.reactnativetouchthroughview.TouchThroughTouchHandlerInterface;
import com.rome2rio.android.reactnativetouchthroughview.TouchThroughTouchHandler;

public class MainActivity extends SplashActivity implements TouchThroughTouchHandlerInterface {
    private TouchThroughTouchHandler touchThroughTouchHandler = new TouchThroughTouchHandler();

    @Override
    protected String getMainComponentName() {
        return "myapp";
    }

    public TouchThroughTouchHandler getTouchThroughTouchHandler() {
        return touchThroughTouchHandler;
    }

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        touchThroughTouchHandler.handleTouchEvent(ev);

        return super.dispatchTouchEvent(ev);
    }
}
```

but that produces this error on `getMainComponentName`:

```
> Task :app:compileDebugJavaWithJavac FAILED
/../../myapp/MainActivity.java:12: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
```

Any ideas on possible workarounds? I feel like this is possibly related to a conflict with `ViewGroupManager` and RNN's `SplashActivity`. Do you know of another way we could apply the `@Override` methods for applications not using `ReactActivity` in `MainActivity.java`?

**Comment by simonhoss** [comment]
Hi @derekblank 

I had a look into the documentation and code from react-native-navigation. If you're using react-native-navigation then you don't need getMainComponentName, because react-native-navigation don't need it. The most important part is the `TouchTroughHandler` and the interface `TouchThroughTouchHandlerInterface` to make it work

Greets

**Comment by derekblank** [comment]
@simonhoss Thanks - I removed `getMainComponentName` on `MainActivity`, and Android built successfully, but it hits the exception "TouchThroughTouchHandlerInterface was not set on app activity" from [TouchThroughWrapper](https://github.com/simonhoss/react-native-touch-through-view/blob/master/android/src/main/java/com/rome2rio/android/reactnativetouchthroughview/TouchThroughWrapper.java#L28-L47).

Perhaps it still doesn't like the way `MainActivity extends SplashActivity implements TouchThroughTouchHandlerInterface`?

Edit/Update: I logged out the app's current activity and realized that react-native-navigation transfers the main activity from [SplashActivity to NavigationActivity](https://github.com/wix/react-native-navigation/blob/0f2ade7f77a5ab2b518b4b5bc285956ded2df489/android/app/src/main/java/com/reactnativenavigation/controllers/NavigationCommandsHandler.java#L525-L548).

**Comment by simonhoss** [comment]
I will have a look on this and give you feedback if I found something.

**Comment by simonhoss** [comment]
@derekblank I created an issue for that here: https://github.com/simonhoss/react-native-touch-through-view/issues/3 

Let us talk there so that we don't fill up this issue

**Comment by traviswimer** [comment]
@martsie Do you still plan to merge in any PRs?

I've been using @simonhoss 's branch, and it works well for me on Android.

On iOS, `pod install` fails because `summary` is empty. This is because it is trying to pull the `description` from `package.json`, which is currently an empty string.

**Comment by martsie** [comment]
Can you recap me on which pull request it is - is it https://github.com/rome2rio/react-native-touch-through-view/pull/10 ? I can merge and publish today if you're happy with it and there are no backdoors hidden in it that would make me a temporary internet celebrity

**Comment by kristfal** [comment]
@martsie I've been using @simonhoss's branch for a while. No issues.

**Comment by simonhoss** [comment]
Maybe it makes sense that I update the pull request first? Because I did some further changes on my repo.

**Comment by traviswimer** [comment]
I looked through most of the code on @simonhoss 's branch the other day and didn't see any issues. 

Just a reminder that it currently isn't working on iOS until a string is added to the `package.json` `description` field. Also, there is a lingering `System.out.println()` in `TouchThroughWrapper.java`, that is presumably left over from debugging.

I can make a PR to fix those if it would be helpful.

**Comment by martsie** [comment]
I'm happy to transfer ownership of the NPM to @simonhoss if you'd like - that may bump up the pace and it sounds like you're all using his branch anyway :)

**Comment by simonhoss** [comment]
@traviswimer a PR is very welcome!

@martsie for me that would be fine I still maintaining my fork. So I would say it makes sense 😉

**Comment by martsie** [comment]
@simonhoss message me on github with your npm username and I'll add you to the package and the change the readme for this project to send people over to your github.

**Comment by simonhoss** [comment]
@martsie My npm username is simonhoss same as in github ;)

**Comment by martsie** [comment]
@simonhoss I've added you as an owner on NPM - send me the word and I'll update the README of this repo to point to yours 👍

**Comment by simonhoss** [comment]
@martsie Thank you. Unfortunately I was not able to make a new npm version, because of some pressure in a other project. But new year, new chance 😄 I will try to change it this week lately next week!

**Comment by simonhoss** [comment]
New version on npm is released. @martsie I think this issue can be closed now :D 

@martsie Should I leave you as maintainer in npm?

**Comment by martsie** [comment]
Yes please @simonhoss - maybe I can help out in the future.

**Comment by simonhoss** [comment]
Alright. Thank you!
